### ISSUE TITLE
CLI commands not working unless app is open

### ISSUE THREAD

**Issue by hwy52** [Chippi/neewer-gl1-pro-cli#1]
We have 2 GL1 Pros. After installing, all commands are working but only if the Neewer Control app is installed and open. Running Windows 11 24H2. Any comments are appreciated. Thank you.

**Comment by Chippi** [comment]
Hey sorry for the late answer. Are you sure you have the Pro version and that the lights are connected to your wifi? Funnily enough, I created this repository due to the same issue with another tool. https://github.com/braintapper/neewer-gl1/issues/2

Technically, if it only works for you while the app is open, then it indicates that your lights don't accept the same handshake codes as for mine. So it's hard for me to debug this since I only have 1 light.

But maybe this works better for you:
https://github.com/braintapper/neewer-gl1
